image: registry.naspersclassifieds.com/olxeu/nexus/starter-next/node-18-pnpm

stages:
    - test

self-test:
    stage: test
#    cache:
#        key: $CI_JOB_NAME
#        paths:
#          - .pnpm-store
    before_script:
        - pnpm config set @nexus:registry https://git.naspersclassifieds.com/api/v4/projects/4482/packages/npm/
        - pnpm config set -- '//git.naspersclassifieds.com/api/v4/projects/4482/packages/npm/:_authToken' ${CI_JOB_TOKEN}
        - pnpm config set store-dir .pnpm-store
        - pnpm install
    script:
        - pnpm run build
        - pnpm run lint:style
        - pnpm run lint
    needs: []
    only:
        - merge_requests
