export enum Actions {
    GET_TEMPLATE_NAME = 'GET_TEMPLATE_NAME',
    GET_TEMPLATE_NAME_REJECTED = 'GET_TEMPLATE_NAME_REJECTED',
    GET_TEMPLATE_NAME_FULFILLED = 'GET_TEMPLATE_NAME_FULFILLED',
    GET_TEMPLATE_NAME_PENDING = 'GET_TEMPLATE_NAME_PENDING',
}
