import Head from 'next/head';

import Counter from '@/components/Counter';
import Random from '@/components/Random';

export default function Home() {
    return (
        <>
            <Head>
                <title>Redux Next Template</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Counter />
                <Random />
            </main>
        </>
    );
}
