import Head from 'next/head'
import {Button} from '@olxui/core';
import {StyleDemo} from '@/components/Demo.style';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Button>Hello</Button>
                <StyleDemo>Style demo</StyleDemo>
            </main>
        </>
    )
}
