import Head from 'next/head';

import { Example } from '@/components/Example';
import { Container, Cell, Row, Col } from '@/components/Layout';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container>
                    <Row>
                        <Col xs="fluid">
                            <Example />
                        </Col>
                        <Col xs={6}>
                            <Cell>hello</Cell>
                        </Col>
                    </Row>
                </Container>
            </main>
        </>
    );
}
