export const GET_RANDOM_NUMBER = 'GET_RANDOM_NUMBER';

export enum Actions {
    GET_RANDOM_NUMBER = 'GET_RANDOM_NUMBER',
    GET_RANDOM_NUMBER_REJECTED = 'GET_RANDOM_NUMBER_REJECTED',
    GET_RANDOM_NUMBER_FULFILLED = 'GET_RANDOM_NUMBER_FULFILLED',
    GET_RANDOM_NUMBER_PENDING = 'GET_RANDOM_NUMBER_PENDING',
}
